name: Build and test
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.os }} ghc-${{ matrix.ghc }} ${{ matrix.configure-flags }}
    strategy:
      matrix:
        cache-key-prefix: [""]  # see `include` below
        configure-flags: [""]  # see `include` below
        os: [ubuntu-24.04]
        ghc: [9.4.7, 9.6.7, 9.8.4, 9.10.1, 9.12.2]
        haddock: [true]  # see `include` below
        include:
        # Include a single build (with latest Linux OS and oldest GHC version)
        # using `--prefer-oldest` to verify that we still build against the
        # lower bounds in the Cabal `build-depends`.
        - cache-key-prefix: prefer-oldest
          configure-flags: --prefer-oldest
          ghc: 9.4.7
          haddock: false
          os: ubuntu-24.04
      fail-fast: false
    uses: GaloisInc/.github/.github/workflows/haskell-ci.yml@v1
    with:
      cache-key-prefix: ${{ matrix.cache-key-prefix }}
      # See Note [Parallelism] in `haskell-ci.yml` for why `--ghc-options='-j'`
      # and `--semaphore`.
      configure-flags: --enable-tests --ghc-options='-Werror=compat -Werror -j' --semaphore ${{ matrix.configure-flags }}
      haddock: ${{ matrix.haddock }}
      ghc: ${{ matrix.ghc }}
      os: ${{ matrix.os }}
