name: Build and test
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.os }} ghc-${{ matrix.ghc }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        ghc: [9.8.4, 9.10.1, 9.12.2]
      fail-fast: false
    uses: GaloisInc/.github/.github/workflows/haskell-ci.yml@v1
    with:
      # See Note [Parallelism] in `haskell-ci.yml` for why `--ghc-options='-j'`
      # and `--semaphore`.
      configure-flags: --enable-tests --ghc-options='-Werror=compat -Werror=default -j' --semaphore
      ghc: ${{ matrix.ghc }}
      os: ${{ matrix.os }}
