name: Build and test
on:
  - push
  - pull_request
jobs:
  test:
    name: ${{ matrix.os }} ghc-${{ matrix.ghc }} ${{ matrix.cache-key-prefix }}
    strategy:
      matrix:
        cache-key-prefix: [""]  # see `include` below
        configure-flags: [""]  # see `include` below
        ghc: [9.4.7, 9.6.7, 9.8.4, 9.10.1, 9.12.2]
        haddock: [true]  # see `include` below
        os: [ubuntu-24.04]
        pre-hook: [""]  # see `include` below
        include:
        # Include a single build (with latest Linux OS and oldest GHC version)
        # using `--prefer-oldest` to verify that we still build against the
        # lower bounds in the Cabal `build-depends`.
        - cache-key-prefix: prefer-oldest
          configure-flags: --prefer-oldest
          ghc: 9.4.7
          haddock: false
          os: ubuntu-24.04
        # Include a single build (with latest Linux OS and latest GHC version)
        # using `cabal-force-upper-bounds` to verify that we actually build
        # against the upper bounds in the Cabal `build-depends`.
        - cache-key-prefix: upper-bounds
          ghc: 9.12.2
          haddock: false
          os: ubuntu-24.04
          pre-hook: |
            curl \
              --fail \
              --location \
              --proto '=https' \
              --show-error \
              --silent \
              --tlsv1.2 \
              https://github.com/nomeata/cabal-force-upper-bound/releases/download/0.1/cabal-force-upper-bound.linux.gz | \
              gunzip > \
              /usr/local/bin/cabal-force-upper-bound
            chmod +x /usr/local/bin/cabal-force-upper-bound
            echo 'packages: .' > cabal.project
            cabal-force-upper-bound --cabal-project *.cabal >> cabal.project
      fail-fast: false
    uses: GaloisInc/.github/.github/workflows/haskell-ci.yml@v1
    with:
      cache-key-prefix: ${{ matrix.cache-key-prefix }}
      # See Note [Parallelism] in `haskell-ci.yml` for why `--ghc-options='-j'`
      # and `--semaphore`.
      configure-flags: --enable-tests --ghc-options='-Werror=compat -Werror -j' --semaphore ${{ matrix.configure-flags }}
      haddock: ${{ matrix.haddock }}
      ghc: ${{ matrix.ghc }}
      os: ${{ matrix.os }}
      pre-hook: ${{ matrix.pre-hook }}
